version: 2
updates:
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    groups:
      direct-dependencies:
        patterns:
          - "ansys-tools-common"          
          - "ansys-tools-visualization-interface"
          - "flask"
          - "pyaedt"
          - "pydantic"
          - "pyqtgraph"
          - "pyside6"
          - "qdarkstyle"
          - "tomli"
      dev-dependencies:
        patterns:
          - "ansys-sphinx-theme>=1.8.2"
          - "ipython"
          - "ipywidgets"
          - "jupyterlab"
          - "jupytext"
          - "nbsphinx"
          - "numpydoc"
          - "pypandoc"
          - "recommonmark"
          - "Sphinx"
          - "sphinx-autobuild"
          - "sphinx-copybutton"
          - "sphinx_design"
          - "prek"
          - "pytest"
          - "pytest-cov"
          - "pytest-qt"
          - "pyvista"
      transitive-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-*"
        - "pyaedt"
        - "pyedb"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(uv)"

  - package-ecosystem: "github-actions" # zizmor: ignore[dependabot-cooldown] cooldown feature is not available for github actions yet.
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 10 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(actions)"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    groups:
      ansys-actions:
        patterns:
          - "ansys/*"
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/pre-commit-hooks"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(pre-commit)"