ignore:
  - "src/ansys/aedt/toolkits/common/ui/**"

comment:
  layout: "diff"
  behavior: default
  require_changes: true  # Avoid coverage comment if no files are changed.

coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 85%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error

codecov:
  notify:
    wait_for_ci: yes
