name: CI - PR
on:
  pull_request:
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: '3.14'
  TESTS_PYTHON_VERSION: '3.10'
  DOCUMENTATION_CNAME: 'aedt.common.toolkit.docs.pyansys.com'
  LIBRARY_NAME: 'ansys-aedt-toolkits-common'
  LIBRARY_NAMESPACE: 'ansys.aedt.toolkits.common'
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Disable default permissions

jobs:

  build-library:
    name: Build library artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/build-library@feat/add-uv-lock-file-check-step
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

