name: "CI"
on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  MAIN_PYTHON_VERSION: '3.12'
  DOCUMENTATION_CNAME: 'aedt.common.toolkit.docs.pyansys.com'
  LIBRARY_NAME: 'ansys-aedt-toolkits-common'
  LIBRARY_NAMESPACE: 'ansys.aedt.toolkits.common'
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Disable default permissions

jobs:


  doc-build:
    name: "Build SH"
    runs-on: [self-hosted, Windows, pyaedt-toolkit]
    timeout-minutes: 30
    steps:
      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@7d84ae825e6d9297a8e99bdbbae20d1b919a0b19 # v4.2

      - name: Build documentation
        uses: ansys/actions/doc-build@fix/miktex-installation-with-recent-choco
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
          add-pdf-html-docs-as-assets: true
          check-links: true

  doc-build-bis:
    name: "Build SH BIS"
    runs-on: [self-hosted, Windows, pyaedt-toolkit]
    needs: doc-build
    timeout-minutes: 30
    steps:
      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@7d84ae825e6d9297a8e99bdbbae20d1b919a0b19 # v4.2

      - name: Build documentation
        uses: ansys/actions/doc-build@fix/miktex-installation-with-recent-choco
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
          add-pdf-html-docs-as-assets: true
          check-links: true

  doc-build-gh:
    name: "Build GH"
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@7d84ae825e6d9297a8e99bdbbae20d1b919a0b19 # v4.2

      - name: Build documentation
        uses: ansys/actions/doc-build@fix/miktex-installation-with-recent-choco
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
          add-pdf-html-docs-as-assets: true
          check-links: true
