name: "CI"
on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  MAIN_PYTHON_VERSION: '3.12'
  DOCUMENTATION_CNAME: 'aedt.common.toolkit.docs.pyansys.com'
  LIBRARY_NAME: 'ansys-aedt-toolkits-common'
  LIBRARY_NAMESPACE: 'ansys.aedt.toolkits.common'
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Disable default permissions

jobs:

  tests_windows:
    name: "Windows Tests"
    runs-on: [self-hosted, Windows, pyaedt-toolkit]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create Python venv
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1

      - name: Install packages for testing
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install -U pip
          pip install -U build wheel
          pip install .[tests] -U

      - name: Export requirements.txt
        run: |
          .\.venv\Scripts\Activate.ps1
          pip freeze > requirements.txt

      - name: Upload requirements.txt
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: requirements-txt
          path: requirements.txt

      # - name: Test AEDT Common API
      #   timeout-minutes: 5
      #   run: |
      #     .\.venv\Scripts\Activate.ps1
      #     pytest -v -m aedt_common_api --cov

      # - name: Test Common API
      #   timeout-minutes: 5
      #   run: |
      #     .\.venv\Scripts\Activate.ps1
      #     pytest -v -m common_api --cov --cov-append

      - name: Test EDB API
        timeout-minutes: 5
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m edb_api --cov --cov-append

      - name: Test REST API
        timeout-minutes: 5
        run: |
          .\.venv\Scripts\Activate.ps1

          pytest -v -m rest_api --cov --cov-append

      - name: Test utils
        timeout-minutes: 5
        run: |
          .\.venv\Scripts\Activate.ps1

          pytest -v -m utils --cov --cov-append

      - name: Test UI
        timeout-minutes: 5
        run: |
          .\.venv\Scripts\Activate.ps1

          pytest -v -m ui --cov --cov-append

      - name: "Combine coverage files"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m coverage html -d .cov\total-html
          python -m coverage xml -o .cov\total.xml

      - name: "Upload coverage results"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          path: .cov/total-html-windows
          name: html-total-coverage-windows

      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          name: codecov-tests-windows
          files: .cov/total.xml
          flags: windows_tests
