name: Nightly

on:
  workflow_dispatch:
  schedule:  # UTC at 0300
    - cron:  '0 3 * * *'


env:
  MAIN_PYTHON_VERSION: '3.14'
  DOCUMENTATION_CNAME: 'aedt.common.toolkit.docs.pyansys.com'
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Disable default permissions

jobs:

  doc-build:
    name: Build documentation
    runs-on: [self-hosted, Windows, pyaedt-toolkit]
    timeout-minutes: 20
    steps:
      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@b0bf9f57d62d2b3fee9f1c0e0c7e390f05e97a4e # v5.0.0

      - name: Build documentation
        uses: ansys/actions/doc-build@7e89e00c5619374a1da8c2e876309d8b15ff0559 # v11.0.3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
          add-pdf-html-docs-as-assets: true
          check-links: true
          optional-dependencies-name: 'all'
          group-dependencies-name: 'doc'

  doc-deploy-dev:
    name: Deploy development documentation
    runs-on: ubuntu-latest
    needs: doc-build
    permissions:
      contents: write # Needed to update files on the gh-pages branch
    steps:
      - uses: ansys/actions/doc-deploy-dev@7e89e00c5619374a1da8c2e876309d8b15ff0559 # v11.0.3
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
